name: Build & Publish to NPM (Production)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: npm install
      - run: npm run test:unit
      - run: npm run build
      - run: npm publish