name: Pull Request on Deployment
on:
  pull_request:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: npm install
      - run: npm run test:unit
      - run: npm run build